### ISSUE TITLE
Missing index triggers failures

### ISSUE THREAD

**Issue by ranjitjhala** [liquid-rust/liquid-rust#73]
See 

1. In the example below, `lr` produces an error about expecting a pair `(int, int)` but only getting an `int`.

   https://github.com/liquid-rust/examples/blob/main/src/bug/mat-bug-00.rs
   
2. In the second example, `lr` just triggers some `fixpoint` "elaboration" crash perhaps due to some malformed sorts in the generated constraints.

   https://github.com/liquid-rust/examples/blob/main/src/bug/mat-bug-01.rs

**Comment by nilehmann** [comment]
@ranjitjhala both errors are caused by the desugaring creating bindings with the wrong sort. There was a bug in the wf checker that let the second one go through, but I fixed that.

**Comment by ranjitjhala** [comment]
Sweet I’ll take a look!
